### ISSUE TITLE
Vector2f ou (RectagleShape, Circle_Shape, etc...)

### ISSUE THREAD

**Issue by Sholde** [Sholde/ProjetLA#10]
J'ai stocker les coord sous forme de vector2f mais a chaque fois on creer un rectangle ou un cercle quand on veut afficher, réfléchis y si tu veux, pour voir si on peut opti, sashant que tout les modules n'ont pas tous les meme propriété.

**Comment by dytq** [comment]
Je ne sais pas si on peut mutualiser les vecteurs ? 
Puis je ne sais pas quoi opti (algo, mémoire ? ) ?
