### ISSUE TITLE
TODO : Provenance du flux du carburant

### ISSUE THREAD

**Issue by dytq** [Sholde/ProjetLA#17]
Problèmes:
- Il faut changer le placement des éléments graphique
- On ne peut pas mettre des noeuds graphique pour simplifier l'affichage ? 
- Réfléchir à un affichage sans croiser les liens 

Phases:
- Entre les vannes transitions
- Entre les vannes reservoirs moteurs

**Comment by Sholde** [comment]
rien compris

**Comment by dytq** [comment]
On sera obligé de le faire la provenance du carburant avec les tuyaux

**Comment by Sholde** [comment]
Trop dur

**Comment by Sholde** [comment]
tu te rend pas compte comment cest chiant de faire de simple forme
